api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
        mime_types: ['multipart/form-data']
    swagger:
        versions: [3]
        api_keys:
          apikey:
            name: Authorization
            type: header
    collection:
        pagination:
            items_per_page: 5
    formats:
       json: ['application/json']
       jsonld: ['application/ld+json']
       html: ['text/html']
       multipart: ['multipart/form-data']